### PR TITLE
Test suffix

### PR DESCRIPTION
**Pull request by honzajavorek**
Except of the reasoning included in the text it also reflects current practice.

### CODE REVIEW

**Comment by XVincentX** [comment]
@hj I agree. Let's merge.

**Comment by honzajavorek** [comment]
What about @Baggz? Mentioning him explicitly as he proposed we drop the suffix.

**Comment by Baggz** [comment]
@honzajavorek @XVincentX 

All good!

_**Nit:**_ CamelCase mixed with a `-test` suffix doesn't look especially nice, but I don't have a better idea at the moment.

:+1: for the reasoning!

**Comment by honzajavorek** [comment]
Okay, I take :+1: of two @apiaryio/core-application elders as sufficient for merging :)

**Pull request merged**
